home(user_is_admin, exoplanets, candidates) ::= <<

<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec pretium lorem. Sed sed neque ipsum. Sed volutpat nibh ut risus pharetra ornare. Ut mattis pellentesque est, ut gravida ligula blandit sit amet. Morbi ac volutpat nisl. Maecenas in odio volutpat est aliquet blandit sed ut enim. Curabitur vel nibh at tellus ullamcorper consectetur.
</p>

<p>
    {exoplanets}
</p>

<p>
    {candidates}
</p>

>>
