#!/usr/bin/env lfescript
;;! -pa ebin
;; This file was generated by server.knot.md.

(defun main
  ([(list "compile")]
    (compile))
  ([(list "test")]
    (test))
  ([_]
    (usage)))

(defun usage []
  (: lfe_io format "Available commands:~n" ())
  (: lfe_io format "  compile: Compiles src/*.lfe to ebin.~n" ())
  (: lfe_io format "  test: Compiles src/*.lfe and test/*.lfe to ebin, and runs eunit:test on~n" ())
  (: lfe_io format "        everything from test/.~n" ())
  )
(defun compile-files [files]
  (: lists map (lambda [file] (compile-file file)) files))

(defun compile-file [filename]
  (: lfe_io format "Compiling: ~s.~n" (list filename))
  (let (((tuple 'ok module) (: lfe_comp file filename '(report #(outdir "ebin")))))
       module))
(defun compile []
  (compile-files (: filelib wildcard "src/*.lfe")))
(defun test []
  (compile)
  (let* ((test-files (: filelib wildcard "test/*.lfe"))
         (compiled-modules (compile-files test-files)))

        (lfe_io:format "Test files: ~p ... Compiled modules: ~p~n" (list test-files compiled-modules))

        (: lists map (lambda [module]
                      (: code purge module)
                      (: code load_file module)
                      (: eunit test module))
                     compiled-modules)))